config/routes.rb
require 'yaml'

Rails.application.routes.draw do
  root to: 'homepages#show', locale: 'en'

  #perform the redirects
  redirects = YAML.load_file('config/redirects.yml')
  redirects.each do |rule|
    get rule["old_path"], to: redirect(rule["new_path"], status: 301)
  end

  CMS_PAGES = %w[
    articles
    evaluations
    insights
    latest_news
    news
    reviews
  ].freeze

  scope ':locale', locale: /en/ do
    resources :articles, only: :show
    resources :evaluations, only: :show
    resources :evidence_hub, only: :index
    resources :insights, only: :show
    resources :lifestages, only: :show
    resources :news, only: %i[index show]
    resources :regional_strategies, only: %i[show]
    resources :reviews, only: :show
    resources :thematic_reviews, only: %i[index show]
    resources :uk_strategies, only: :show
    resources :what_works, only: :show

    # Static pages
    get 'get-involved' => 'static_pages#be_involved'
    get 'impact-principles' => 'static_pages#impact_principles'

    # Preview pages
    get '/:page_type/:id/preview' => 'documents_preview#show',
        page_type: Regexp.union(CMS_PAGES)

    # Search page
    resources :search_results, only: 'index', path: 'search'
  end

  resources :cookie_policy_acceptances, only: :create

  # Styleguide
  get '/styleguide', to: 'styleguide#home'
  get 'styleguide/:page' => 'styleguide#show'

  # Errors
  get 'not_found', to: 'errors#not_found'
  get 'service_unavailable', to: 'errors#service_unavailable'

  get '*path', to: 'catch_all#index'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def be_involved; end

  def impact_principles; end
end

app/views/static_pages/be_involved.html.erb
<% title "#{t('fincap.get_involved.title')} | #{t('fincap.page_title')}" %>
<div class="l-constrained">
  <%= render '/components/hero',
   img_src: image_url('static_pages/hero-get-involved.jpg'),
   description: t('fincap.get_involved.title')
  %>

  <div class="row">
    <div class="l-2col-main">
      <h1><%= t('fincap.get_involved.head') %></h1>
      <dl class="list list--numbered">
        <dt class="list--numbered__title">
          <%= t('fincap.get_involved.list.sign_up.title') %>
        </dt>
        <dd class="list--numbered__content">
          <%= raw t(
            'fincap.get_involved.list.sign_up.content_html',
            link: (link_to 'IMPACT principles', 'impact-principles')) %>
        </dd>
        <dt class="list--numbered__title">
          <%= t('fincap.get_involved.list.use.title') %>
        </dt>
        <dd class="list--numbered__content">
          <%= raw t(
            'fincap.get_involved.list.use.content_html',
            link_evaluation_toolkit: (link_to 'Evaluation Toolkit', article_path('en', 'evaluation-toolkit-overview')),
            link_evidence_hub: (link_to 'Evidence Hub', evidence_hub_index_path)) %>
        </dd>
        <dt class="list--numbered__title">
            <%= t('fincap.get_involved.list.talk_money_week.title') %>
        </dt>
        <dd class="list--numbered__content">
          <%= raw t('fincap.get_involved.list.talk_money_week.content_html',
            link: (link_to 'here', article_path('en', 'talk-money-week'))) %>
        </dd>
        <dt class="list--numbered__title">
          <%= t('fincap.get_involved.list.up_to_date.title') %>
        </dt>
        <dd class="list--numbered__content">
          <%= raw t('fincap.get_involved.list.up_to_date.content_html',
            link_twitter: (link_to 'Twitter', t('fincap.links_external.twitter')),
            link_linkedin: (link_to 'LinkedIn', t('fincap.links_external.linkedin'))) %>
        </dd>
        <dt class="list--numbered__title">
          <%= t('fincap.get_involved.list.share.title') %>
        </dt>
        <dd class="list--numbered__content">
          <%= raw t('fincap.get_involved.list.share.content_html',
            link: (link_to 'linkedin@fincap.org.uk', 'mailto:linkedin@fincap.org.uk')) %>
        </dd>
      </dl>
      <h2><%= t('fincap.get_involved.talk.title') %></h2>
      <p><%= raw t('fincap.get_involved.talk.para_1', url: (link_to 'whatworks@fincap.org.uk', 'mailto:whatworks@fincap.org.uk')) %></p>
      <p><%= raw t('fincap.get_involved.talk.para_2', url: (link_to 'talkmoneyweek@fincap.org.uk', 'mailto:talkmoneyweek@fincap.org.uk')) %></p>
    </div>
  </div>
</div>

app/views/static_pages/impact_principles.html.erb
<% title "#{t('fincap.impact_principles.title')} | #{t('fincap.page_title')}" %>
<div class="l-constrained">
  <%= render '/components/hero',
    img_src: image_url('static_pages/hero-impact-principles.jpg'),
    description: t('fincap.impact_principles.title'),
    hero_colour: 'hero--yellow'
  %>
  <div class="row">
    <div class="l-2col-main body-content">
      <%= t('fincap.impact_principles.intro_html', link: (link_to 'whatworks@fincap.org.uk', 'mailto:whatworks@fincap.org.uk')) %>
      <ul class="list list--lettered">
        <% t('fincap.impact_principles.list').each do |item| %>
          <li class="list--lettered-item">
            <div class="list--lettered-item__letter" aria-hidden="true">
              <%= item[:letter] %>
            </div>
            <div class="list--lettered-item__content">
              <p class="list--lettered-item__title">
                <%= item[:heading] %>
              </p>
              <p class="list--lettered-item__inner-content">
                <%= item[:content] %>
              </p>
            </div>
          </li>
        <% end %>
      </ul>
      <h2><%= t('fincap.impact_principles.support.header') %></h2>
      <p><%= t('fincap.impact_principles.support.intro') %></p>
      <ul>
        <% t('fincap.impact_principles.support.list',
          link_insightAndResearch: (link_to 'insight and research', 'https://www.moneyadviceservice.org.uk/en/corporate/research')
        ).each do |item| %>
          <li><%= raw item %></li>
        <% end %>
      </ul>
      <p><%= t('fincap.impact_principles.support.para_1') %></p>
      <p><%= raw t('fincap.impact_principles.support.para_2', link: (link_to 'whatworks@fincap.org.uk', 'mailto:whatworks@fincap.org.uk')) %></p>
    </div>
    <div class="l-2col-side">
      <ul class="list list--grouped-cta">
        <li>
          <%= link_to 'UK Financial Capability Strategy', uk_strategy_path(locale: params[:locale], id: 'uk-strategy') %>
        </li>
      </ul>
      <div class="download-box">
        <svg xmlns="http://www.w3.org/2000/svg" class="download-box__icon svg-icon svg-icon--download" focusable="false">
          <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-icon--download"></use>
        </svg>
        <h3 class="download-box__title">Download</h3>
        <ul class="download-box__list">
          <li class="download-box__list-item">
            <%= link_to 'Evidence and Evaluation – Strategy Extract', 'https://masassets.blob.core.windows.net/fincap-cms/files/000/000/112/original/Evidence_and_Evaluation_Strategy_Extract.pdf', class: 'download-box__list-item-link' %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>