config/routes.rb
require 'yaml'

Rails.application.routes.draw do
  root to: 'homepages#show', locale: 'en'

  #perform the redirects
  redirects = YAML.load_file('config/redirects.yml')
  redirects.each do |rule|
    get rule["old_path"], to: redirect(rule["new_path"], status: 301)
  end

  CMS_PAGES = %w[
    articles
    evaluations
    insights
    latest_news
    news
    reviews
  ].freeze

  scope ':locale', locale: /en/ do
    resources :articles, only: :show
    resources :evaluations, only: :show
    resources :evidence_hub, only: :index
    resources :insights, only: :show
    resources :lifestages, only: :show
    resources :news, only: %i[index show]
    resources :regional_strategies, only: %i[show]
    resources :reviews, only: :show
    resources :thematic_reviews, only: %i[index show]
    resources :uk_strategies, only: :show
    resources :what_works, only: :show

    # Static pages
    get 'get-involved' => 'static_pages#be_involved'
    get 'impact-principles' => 'static_pages#impact_principles'

    # Preview pages
    get '/:page_type/:id/preview' => 'documents_preview#show',
        page_type: Regexp.union(CMS_PAGES)

    # Search page
    resources :search_results, only: 'index', path: 'search'
  end

  resources :cookie_policy_acceptances, only: :create

  # Styleguide
  get '/styleguide', to: 'styleguide#home'
  get 'styleguide/:page' => 'styleguide#show'

  # Errors
  get 'not_found', to: 'errors#not_found'
  get 'service_unavailable', to: 'errors#service_unavailable'

  get '*path', to: 'catch_all#index'
end

app/views/shared/_country_list.html.erb
<div class="bordered-box">
  <div class="bordered-box__inner">
    <h3 class="bordered-box__title"><%= I18n.t('fincap.countries.title') %></h3>
    <div class="bordered-box__content">
      <p><%= I18n.t('fincap.countries.intro') %></p>
      <ul class="list list--countries">
        <% I18n.t('fincap.countries_list').each do |country| %>
          <li class="list--countries-item">
            <svg xmlns="http://www.w3.org/2000/svg" class="list--countries-icon svg-icon svg-icon--country" focusable="false">
              <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-icon--<%= country[:region] %>"></use>
            </svg>
            <%= link_to(country[:text], strategy_path(country), class: 'list--countries-link') %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_data_types.html.erb
<ul class="evidence-types">
  <% presenter.data_type_keys.each do |data_type| %>
    <li class="evidence-types__item data-types__<%= "#{data_type.downcase}" %>">
      <%= render 'shared/evidence_types', icon: presenter.data_type_icon(data_type), text: data_type %>
    </li>
  <% end %>
</ul>

app/views/shared/_error.html.erb
<h2>Error <%= error[:status] %><h2>
<p><%= error[:message] %></p>
<p>Your request resulted in an error. Please try again.</p>
<p><%= link_to 'Go back to evidence summaries', evidence_hub_index_path %></p>

app/views/shared/_feedback.html.erb
<%= render 'components/feedback', content: content %>

app/views/shared/_google_tag_manager.erb
<noscript>
  <iframe src="//www.googletagmanager.com/ns.html?id=<%= Rails.application.config.google_tag_manager_id %>"
          height="0" width="0" style="display:none;visibility:hidden"
          title="Google Tag Manager"></iframe>
</noscript>
<script>
    (function(w, d, s, l, i) {
        w[l] = w[l] || [];
        w[l].push({'gtm.start': new Date().getTime(), event: 'gtm.js'});
        var f = d.getElementsByTagName(s)[0],
            j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
        j.async = true;
        j.src = '//www.googletagmanager.com/gtm.js?id=' + i + dl;
        f.parentNode.insertBefore(j, f.nextSibling);
    })(window, document, 'script', 'dataLayer', '<%= Rails.application.config.google_tag_manager_id %>');
</script>

app/views/shared/_header.html.erb
<header data-site-header data-dough-component="Header" data-dough-header-config='{"textClose":"Close Search"}' class="header">
  <div class="header-wrap">
    <div class="header-content">
      <div class="header-logo">
        <a href="/" class="header-logo__link">
          <%= image_tag("logo.png", alt: "t('layouts.base.title')", class: 'header-logo__img') %>
        </a>
      </div>
      <ul class="header-links">
        <li class="header-links__link">
          <%= link_to('Contact us', article_path('en', 'contact-us')) %>
        </li>
        <li class="header-links__link">
          <%= link_to 'Get involved', get_involved_path %>
        </li>
      </ul>
      <div class="mobile-header__content">
        <a data-mobile-nav-button href="#" role="button" class="btn btn--orange mobile-header__nav-button">Menu</a>
        <a data-mobile-search-button href="#" class="btn btn--primary search__submit--icon mobile-header__search-button" role="button" >
          <svg xmlns="http://www.w3.org/2000/svg" class="search-icon__show svg-icon svg-icon--search" focusable="false">
            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-icon--search"></use>
          </svg>
          <svg xmlns="http://www.w3.org/2000/svg" class="search-icon__hide show svg-icon svg-icon--search" focusable="false">
            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-icon--close"></use>
          </svg>
          <span data-mobile-search-text class="visually-hidden">Open Search</span>
        </a>
      </div>

    </div>
    <div class="mobile-header__search">
      <div class="mobile-header__search-bar">
        <%= render 'shared/search', location: 'navigation-mobile' %>
      </div>
    </div>
  </div>
</header>

app/views/shared/_large_cta.html.erb
<a href=<%= url %> class="large-cta">
  <svg xmlns="http://www.w3.org/2000/svg" class="large-cta__icon svg-icon svg-icon--<%= "#{icon}" %>" focusable="false">
    <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-icon--<%= "#{icon}" %>"></use>
  </svg>
  <span class="large-cta__text"><%= text %></span>
</a>

app/views/shared/_latest_news.html.erb
<% num_of_items = 3 if local_assigns[:num_of_items].nil? %>
<div class="latest-news">
  <div class="latest-news__inner">
    <h3 class="latest-news__title">Latest News</h3>
    <svg xmlns="http://www.w3.org/2000/svg" class="latest-news__icon svg-icon svg-icon--latest-news" focusable="false">
      <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-icon--latest-news"></use>
    </svg>
    <ul class="latest-news__list">
      <% present_collection(latest_news.first(num_of_items)).each do |item| %>
        <li class="latest-news__list-item">
          <span class="latest-news__list-item__date"><%= item.order_by_date_component %></span>
          <p class="latest-news__list-item__text"><%= item.title %></p>
          <%= link_to 'Read more', item.full_path, class: "latest-news__list-item__cta" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_life_stages.html.erb
<div class="bordered-box bordered-box--green">
  <div class="bordered-box__inner">
    <h3 class="bordered-box__title">Life stages across the UK</h3>
    <div class="bordered-box__content">
      <p>Different life stages have an effect on people's ability to manage their money.</p>
      <ul class="list list--links">
        <% I18n.t('fincap.life_stages').each do |stage| %>
          <li>
            <%= link_to(stage[:text], lifestage_path(locale: 'en', id: stage[:slug]), id: stage[:slug] ) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_maps_banner.html.erb
<div class="l-maps_banner">
  <div class="l-constrained">
    <div class="l-maps_banner__content">
      <span class="maps_banner__mps-text"><%= t('fincap.maps_banner.strapline_html', url: 'https://www.maps.org.uk/wellbeing') %></span>

      <a href="https://moneyandpensionsservice.org.uk/" target="_blank" class="maps_banner__link">
        <span class="maps_banner__mps-logo"></span>
        <span class="visually-hidden">Opens in a new window</span>
      </a>
    </div>
  </div>
</div>

app/views/shared/_research.html.erb
<div class="coloured-box">
  <h2 class="coloured-box__title">Research &amp; Evaluation</h2>
  <ul class="list list--links coloured-box__list">
    <li><a href="#">List item 1</a></li>
    <li><a href="#">List item 2</a></li>
    <li><a href="#">List item 3</a></li>
    <li><a href="#">List item 4</a></li>
  </ul>
</div>

app/views/shared/_research_and_evaluation.html.erb
<div class="l-2col l-2col-no-margin l-2col-flex">
  <div class="l-2col-even coloured-box">
    <h2 class="coloured-box__title">Research and findings</h2>
    <ul class="list list--links coloured-box__list">
      <% I18n.t('fincap.research_evaluation.findings').each do |link| %>
        <li>
          <%= link_to(link[:text], article_path(locale: 'en', id: link[:slug])) %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="l-2col-even coloured-box">
    <h2 class="coloured-box__title">Evaluate your programme</h2>
    <ul class="list list--links coloured-box__list">
      <% I18n.t('fincap.research_evaluation.existing').each do |page| %>
        <li><%= link_to(page[:text], define_path(page)) %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_teaser_group.html.erb
<% (1..3).each do |n| %>
  <div class="teaser-box">
    <img src="<%= template.teaser_image_component(n) %>" class="teaser-box__image-ratio" />
    <div class="teaser-box__content">
      <h3 class="teaser-box__title"><%= template.teaser_title_component(n) %></h3>
      <p class="teaser-box__content-text"><%= template.teaser_text_component(n) %></p>
      <a href="<%= template.teaser_link_component(n).first[:href] %>" class="teaser-box__cta btn btn--primary">
        <%= template.teaser_link_component(n).first[:text] %>
      </a>
    </div>
  </div>
<% end %>

app/views/shared/_tooltip.html.erb
<div class="tooltip" data-dough-component="Tooltip" role="tooltip">
  <button class="tooltip__trigger" data-tooltip-button aria-describedby='<%= "#{id}" %>'>
    <%= "#{trigger}".html_safe %>
  </button>
  <div class="tooltip__content js-is-hidden" data-tooltip-content id='<%= "#{id}" %>'>
    <%= "#{content}".html_safe %>
  </div>
</div>